language: php
php:
  - 7.2
  - 7.3
  - 7.4

services:
  - postgresql

env:
  global:
    - APP_NAME=metadata
  matrix:
    - CLOUD=nextcloud CORE_BRANCH=stable13
    - CLOUD=nextcloud CORE_BRANCH=stable14
    - CLOUD=nextcloud CORE_BRANCH=stable15
    - CLOUD=nextcloud CORE_BRANCH=stable16
    - CLOUD=nextcloud CORE_BRANCH=stable17
    - CLOUD=nextcloud CORE_BRANCH=stable18
    - CLOUD=nextcloud CORE_BRANCH=master
    - CLOUD=owncloud CORE_BRANCH=v10.1.1
    - CLOUD=owncloud CORE_BRANCH=stable10

matrix:
  exclude:
    - php: 7.3
      env: CLOUD=nextcloud CORE_BRANCH=stable13
    - php: 7.3
      env: CLOUD=owncloud CORE_BRANCH=v10.1.1
    - php: 7.4
      env: CLOUD=nextcloud CORE_BRANCH=stable13
    - php: 7.4
      env: CLOUD=nextcloud CORE_BRANCH=stable14
    - php: 7.4
      env: CLOUD=nextcloud CORE_BRANCH=stable15
    - php: 7.4
      env: CLOUD=nextcloud CORE_BRANCH=stable16
    - php: 7.4
      env: CLOUD=nextcloud CORE_BRANCH=stable17
    - php: 7.4
      env: CLOUD=owncloud CORE_BRANCH=v10.1.1
    - php: 7.4
      env: CLOUD=owncloud CORE_BRANCH=stable10
  allow_failures:
    - php: 7.2

before_install:
  - if [ $CLOUD = 'nextcloud' ]; then wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh; fi
  - if [ $CLOUD = 'owncloud' ]; then wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh; fi
  - if [ $CLOUD = 'owncloud' ]; then nvm install stable; fi
  - if [ $CLOUD = 'owncloud' ]; then curl -sSfL -o ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-6.5.phar; fi
  - if [ $CLOUD = 'owncloud' ]; then ln -s $PWD ../$APP_NAME; fi
  - . ./before_install.sh $APP_NAME $CORE_BRANCH pgsql
  - if [ $CLOUD = 'nextcloud' ]; then cd ../server; fi
  - if [ $CLOUD = 'owncloud' ]; then cd ../core; fi

  - ./occ check
  - ./occ status
  - ./occ app:enable $APP_NAME
  - ./occ app:list

script:
  - cd apps/$APP_NAME/
  
  # Run phpunit tests
  - cd tests
  - phpunit --configuration phpunit.xml
